name: update readme

on:
  pull_request:
    types:
      - closed


jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: git configure
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Make changes and commit
        run: |
          git switch -c update-readme
          node index.js
          git add README.md
          git commit -m "update README with latest list"
          git push origin update-readme

      - name: create and merge PR
        run: |
          gh pr create --base=main --head=update-readme --f
          # sleep 15
          # gh pr merge -s -d
        env: 
          GH_TOKEN: ${{ github.token }}
